import type { Game } from "../../../../types/game";

export const games: Game[] = [
    {
        id: 1,
        name: "World of Warcraft",
        platform: ["pc"],
        category: ["mmorpg", "fantasy", "pve", "pvp", "open-world"],
        type: ["Party", "Streams"],
        streamers: [
            {
                id: 101,
                username: "Asmongold",
                channel_name: "Asmongold TV",
                description: "Hardcore raiding and PvP since 2009!",
                followers: 3200000,
            },
            {
                id: 102,
                username: "MythicRaider",
                channel_name: "WoW Endgame",
                description: "Mythic raids and dungeon guides.",
                followers: 450000,
            },
        ],
    },
    {
        id: 2,
        name: "Fortnite",
        platform: ["pc", "browser"],
        category: ["battle-royale", "shooter", "action"],
        type: ["Matches", "Streams"],
        streamers: [
            {
                id: 201,
                username: "Ninja",
                channel_name: "Ninja's Fortnite",
                description: "High-energy gameplay and trickshots!",
                followers: 18000000,
            },
            {
                id: 202,
                username: "Tfue",
                channel_name: "Tfue Clips",
                description: "Competitive Fortnite player.",
                followers: 11000000,
            },
        ],
    },
    {
        id: 3,
        name: "Minecraft",
        platform: ["pc", "browser"],
        category: ["sandbox", "open-world", "survival"],
        type: ["Party", "Streams"],
        streamers: [
            {
                id: 301,
                username: "Dream",
                channel_name: "Dream SMP",
                description: "Speedruns and crazy Minecraft challenges!",
                followers: 25000000,
            },
            {
                id: 302,
                username: "Technoblade",
                channel_name: "Technoblade Never Dies",
                description: "Minecraft PvP god.",
                followers: 5000000,
            },
        ],
    },
    {
        id: 4,
        name: "League of Legends",
        platform: ["pc"],
        category: ["moba", "strategy", "pvp"],
        type: ["Matches", "Streams"],
        streamers: [
            {
                id: 401,
                username: "Faker",
                channel_name: "Faker’s Streams",
                description: "The Unkillable Demon King.",
                followers: 7000000,
            },
            {
                id: 402,
                username: "Tyler1",
                channel_name: "T1 Alpha",
                description: "Most toxic (and entertaining) LoL streamer.",
                followers: 3500000,
            },
        ],
    },
    {
        id: 5,
        name: "Valorant",
        platform: ["pc"],
        category: ["fps", "shooter", "tactical"],
        type: ["Matches", "Streams"],
        streamers: [
            {
                id: 501,
                username: "Shroud",
                channel_name: "Shroud Plays",
                description: "Aimbot-level FPS skills.",
                followers: 10000000,
            },
            {
                id: 502,
                username: "TenZ",
                channel_name: "TenZ Highlights",
                description: "Pro Valorant player for Sentinels.",
                followers: 3000000,
            },
        ],
    },
    {
        id: 6,
        name: "Among Us",
        platform: ["pc", "browser"],
        category: ["social", "strategy", "Party"],
        type: ["Party", "Streams"],
        streamers: [
            {
                id: 601,
                username: "Pokimane",
                channel_name: "Pokimane’s Lobby",
                description: "Chaotic Among Us lobbies.",
                followers: 9000000,
            },
            {
                id: 602,
                username: "xQc",
                channel_name: "xQcOW",
                description: "The most unpredictable impostor.",
                followers: 12000000,
            },
        ],
    },
    {
        id: 7,
        name: "Cyberpunk 2077",
        platform: ["pc"],
        category: ["open-world", "rpg", "sci-fi"],
        type: ["Streams"],
        streamers: [
            {
                id: 701,
                username: "CDNThe3rd",
                channel_name: "Cyberpunk Adventures",
                description: "Exploring Night City’s secrets.",
                followers: 1500000,
            },
        ],
    },
    {
        id: 8,
        name: "Apex Legends",
        platform: ["pc"],
        category: ["fps", "battle-royale", "shooter"],
        type: ["Matches", "Streams"],
        streamers: [
            {
                id: 801,
                username: "Aceu",
                channel_name: "Aceu’s Apex",
                description: "Movement king in Apex.",
                followers: 2000000,
            },
        ],
    },
    {
        id: 9,
        name: "Genshin Impact",
        platform: ["pc", "browser"],
        category: ["open-world", "anime", "rpg"],
        type: ["Streams"],
        streamers: [
            {
                id: 901,
                username: "Tectone",
                channel_name: "Tectone’s Gacha Madness",
                description: "Whaling and suffering in gacha hell.",
                followers: 800000,
            },
        ],
    },
    {
        id: 10,
        name: "Call of Duty: Warzone",
        platform: ["pc"],
        category: ["fps", "battle-royale", "military"],
        type: ["Matches", "Streams"],
        streamers: [
            {
                id: 1001,
                username: "DrDisrespect",
                channel_name: "The Doc",
                description: "Violence, speed, and momentum.",
                followers: 5000000,
            },
        ],
    },
    {
        id: 11,
        name: "Dota 2",
        platform: ["pc"],
        category: ["moba", "strategy", "pvp"],
        type: ["Matches", "Streams"],
        streamers: [
            {
                id: 1101,
                username: "Gorgc",
                channel_name: "Gorgc Streams",
                description: "High MMR Dota 2 gameplay.",
                followers: 600000,
            },
        ],
    },
    {
        id: 12,
        name: "Rocket League",
        platform: ["pc"],
        category: ["sports", "racing", "competitive"],
        type: ["Matches", "Streams"],
        streamers: [
            {
                id: 1201,
                username: "SquishyMuffinz",
                channel_name: "Squishy’s RL",
                description: "Pro Rocket League player.",
                followers: 1200000,
            },
        ],
    },
    {
        id: 13,
        name: "Grand Theft Auto V",
        platform: ["pc"],
        category: ["open-world", "action", "sandbox"],
        type: ["Streams"],
        streamers: [
            {
                id: 1301,
                username: "Summit1g",
                channel_name: "Summit’s GTA RP",
                description: "Roleplaying in Los Santos.",
                followers: 5500000,
            },
        ],
    },
    {
        id: 14,
        name: "Counter-Strike 2",
        platform: ["pc"],
        category: ["fps", "shooter", "tactical"],
        type: ["Matches", "Streams"],
        streamers: [
            {
                id: 1401,
                username: "s1mple",
                channel_name: "s1mple CS",
                description: "Best CS2 player in the world.",
                followers: 3000000,
            },
        ],
    },
    {
        id: 15,
        name: "Roblox",
        platform: ["pc", "browser"],
        category: ["sandbox", "social", "mmo"],
        type: ["Party", "Streams"],
        streamers: [
            {
                id: 1501,
                username: "KreekCraft",
                channel_name: "Kreek’s Roblox",
                description: "Funny Roblox moments.",
                followers: 2500000,
            },
        ],
    },
];
